### PR TITLE
A good pull :D

### PR DESCRIPTION
**Pull request by Kaliom**
Some basic stuff is implanted :D

### CODE REVIEW

**Comment by Kaliom** [comment]
It still had the first commit in it, sorry D:

**Comment by CylonicRaider** [comment]
Multiple (partially picky :frowning:) comments:
1. I'd escape the `>` character in the smiley in the title (It's HTML!).
2. `onclick` doesn't need `javascript:` (that's only for JS URL's); might be even invalid.
3. The empty lines around the canvas are asymmetric.
4. `petri.js` has two-space indents.
5. `style.css` doesn't use 1TBS (the closing parentheses are at the same level as the content, and – _personal note_ – it looks somehow weird).

**Comment by CylonicRaider** [comment]
As a last (_very_ picky) point, one could still note (as GitHub does) the missing newlines in the ends of `.gitignore` and `petri.js`.

OTOH, +1 for the canvas additions. :smile:

**Comment by CylonicRaider** [comment]
OK, I'll merge it, and add the newlines myself. You can sync that back later.

**Pull request merged**
